### ISSUE TITLE
Set defaultProps together with propTypes

### ISSUE THREAD

**Issue by arjunmehta** [reactjs/prop-types#37]
Maybe this already exists, but right now I have to set defaultProps on my propTypes as a separate definition:

```javascript
import PropTypes from 'prop-types';

...

MyComponent.propTypes = {
  propA: PropTypes.func,
  propB: PropTypes.bool.isRequired,
  propC: PropTypes.string
};

MyComponent.defaultProps = {
  propA: () => {},
  propC: 'Default String'
};
```

This can be really annoying for long lists of props. Not sure how this matches up with react philosophy, but it would be good to have a way to set types and defaults in one go to reduce code repetition and reduce opportunities for bugs:

```javascript
PropTypes.setPropTypes(MyComponent, {
  propA: { type: PropTypes.func, default: () => {} },
  propB: PropTypes.bool.isRequired,
  propC: { type: PropTypes.string, default: 'Default String' }
})
```

**Comment by gaearon** [comment]
This is intentional, as `defaultProps` is a core part of the API (and is important in production) whereas `propTypes` give you some development-time validation, and in some cases can be replaced by Flow or TypeScript. We don’t want to conflate these two APIs, even at the expense of some perceived duplication. Thanks for suggestion though!

**Comment by arjunmehta** [comment]
@gaearon Makes sense! Thanks for the explanation :)
