### ISSUE TITLE
Why react should be declared as peerDependencies and prop-type as dependency ?

### ISSUE THREAD

**Issue by pgn-vole** [reactjs/prop-types#44]
Hi Team, I've a question regarding the suggestion made in the readme on how to depend on `prop-type`:

https://github.com/reactjs/prop-types#how-to-depend-on-this-package

As a library maintainer both react and prop-type should be considered as external dependencies to my libraries as they should come from the environement using them and they should not be merged . So far I always thought that the peerDependency was the correct way of listing those dependencies (`react` and `react-dom` so far). 
Now I'm a buit confused because you are suggesting to use prop-type as dependencies and not peerDependencies, what makes prop-types different to react ?

**Comment by gaearon** [comment]
I think the main difference is the user tends to know which version of React they need, but might not care about `prop-types`. So letting the user choose with `react` seems more important. Since peer dependencies are generally a pain, it would be great to reduce the reliance on them, and this seems like a case where it could work.

But I agree the distinction is fuzzy.

**Comment by benwiley4000** [comment]
Thanks for the explanation; perhaps some version could make it to the README. I think the key thing to understand is that `prop-types` will still be bundled during the user's compile step, not the library's, though *unlike* `react` it's unnecessary for the user's app to explicitly depend on `prop-types`.

**Comment by pgn-vole** [comment]
Thanks for the explanation @gaearon. Would you suggest that libraries should bundle `prop-types` or reference it (as they do with React)  ?

**Comment by jedwards1211** [comment]
Well the other thing no one's mentioned here is if various components depend on incompatible versions of `prop-types`, it's not a problem, because each can independently use the version it needs, whereas everything has to be using the same version of React.

**Comment by gaurav5430** [comment]
with a monorepo setup, where a lot of packages from the monorepo are going to be used across consumers, we have figured that it makes sense to just add it as a peer dependency instead of a dependency. I mean, it could very well be a dependency sure, but it just makes sense to treat it as other dependencies
